resources:
  repositories:
  - repository: azure-devops-tools
    type: github
    endpoint: 'GitHub Connection Magnus'
    name: 'nexus-link/nexus-azure-devops-tools'
    ref: 'refs/heads/master'

trigger:
  branches:
    include:
    - master
    - dev
  paths:
    include:
    - 'src/Capabilities.AsyncRequestMgmt.Abstract/*'

jobs:
- template: 'templates/netcore/v1/jobs/nuget.yml@azure-devops-tools'
  parameters:
    jobName: 'Capabilities_AsyncRequestMgmt_Abstract'
    testProjectsPath: 'tests/AM.UnitTests/*.csproj'
    nugetProjectsPath: 'src/Capabilities.AsyncRequestMgmt.Abstract/*.csproj'
    nuGetFeedType: external
    publishFeedCredentials: 'prd-nexus-nuget-external'
    publishVstsFeed: 'Nexus Libs/nexus-nugets'
